return {
  ["nvim-treesitter/nvim-treesitter"] = {
    ensure_installed = {
      "bash",
      "cmake",
      "css",
      "dockerfile",
      "dot",
      "html",
      "http",
      "java",
      "javascript",
      "hjson",
      "latex",
      "lua",
      "make",
      "markdown",
      "python",
      "r",
      "rst",
      "scss",
      "vim",
      "vue",
      "yaml",
    },
  },
}
